asPlayerJoined:
  message: "Welcome to the server, %s"
city:
  message:
    success: "Success! I send this inform for verification admins"
    failure:
      short: "Failure. Arguments is very short. Use: /city <x> <y> <z>"
      large: "Failure. Arguments is very large. Use: /city <x> <y> <z>"
jda:
  city:
    channel: " " #Message channel
    message:
      color: "#FF0000" #Embed color in HEX(Integer)
      title: "Knock-knock, here is an request for the city"
      desc: "Coordinates:"
      author: "Author:"
  serverId: "" #Server id
  prefix: "!" #Standard Prefix
  version: "${version}"
  token: "there your discord token" #Bot token. See https://discord.com/developers to get this